# このconfigは、 dockerでMisskey本体を起動せず、 redisとpostgresql などだけを起動します

services:
  redis:
    restart: always
    image: 'docker.dragonflydb.io/dragonflydb/dragonfly'
    ports:
      - "6379:6379"
    command: ['--default_lua_flags=allow-undeclared-keys','--lock_on_hashtags']
    ulimits:
      memlock: -1
    volumes:
      - ./redis:/data
    healthcheck:
      test: "redis-cli ping"
      interval: 5s
      retries: 20

  db:
    restart: always
    image: postgres:18-alpine
    ports:
      - "5432:5432"
    env_file:
      - .config/docker.env
    volumes:
      - ./db:/var/lib/postgresql
    healthcheck:
      test: "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"
      interval: 5s
      retries: 20

#  sensitive-detector:
#    image: kanarikanaru/sensitive-detector:main-0.0.2-hanami.26-afa0a9e@sha256:f47d2c81daa87c4b9f10d64981209b4147b95d335014580de0c48f33d27b4f7c
#    restart: unless-stopped
#    env_file:
#      - .config/sensitive-detector.env
#    ports:
#      - "127.0.0.1:3009:3009"
#    volumes:
#      - ./.config/sensitive-detector.mjs:/config/config.mjs:ro
#    deploy:
#      resources:
#        limits:
#          memory: 2g
#        reservations:
#          memory: 512m
#    security_opt:
#      - no-new-privileges:true
#    cap_drop:
#      - ALL
#    read_only: true
#    tmpfs:
#      - /tmp
#    logging:
#      driver: json-file
#      options:
#        max-size: "10m"
#        max-file: "3"

#  meilisearch:
#    restart: always
#    image: getmeili/meilisearch:v1.3.4
#    environment:
#      - MEILI_NO_ANALYTICS=true
#      - MEILI_ENV=production
#    env_file:
#      - .config/meilisearch.env
#    volumes:
#      - ./meili_data:/meili_data

