services:
  app:
    build:
      context: .
      dockerfile: Dockerfile

    volumes:
      - ../:/workspace:cached
      - node_modules:/workspace/node_modules

    command: sleep infinity

    networks:
      - internal_network
      - external_network

  redis:
    restart: unless-stopped
    image: 'docker.dragonflydb.io/dragonflydb/dragonfly'
    command: ['--default_lua_flags=allow-undeclared-keys','--lock_on_hashtags']
    networks:
      - internal_network
    ulimits:
      memlock: -1
    volumes:
      - redis-data:/data
    healthcheck:
      test: "redis-cli ping"
      interval: 5s
      retries: 20

  db:
    restart: unless-stopped
    image: postgres:17-alpine
    networks:
      - internal_network
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: misskey
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"
      interval: 5s
      retries: 20

  meilisearch:
    restart: always
    image: getmeili/meilisearch:latest
    environment:
      - MEILI_NO_ANALYTICS=true
      - MEILI_ENV=development
    env_file:
      - ./meilisearch.env
    networks:
      - internal_network
    volumes:
      - ./meili_data:/meili_data

  hanamisearch:
    restart: always
    image: getmeili/meilisearch:latest
    environment:
      - MEILI_NO_ANALYTICS=true
      - MEILI_ENV=development
    env_file:
      - ./hanamisearch.env
    networks:
      - internal_network
    volumes:
      - ./hanami_data:/meili_data

  kafka:
    image: 'bitnami/kafka:latest'
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_CONTROLLER_BROKER_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
    networks:
      - internal_network

  kafka-ui:
    image: 'provectuslabs/kafka-ui:latest'
    depends_on:
      - kafka
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
    networks:
      - internal_network

volumes:
  postgres-data:
  redis-data:
  node_modules:
  meili_data:
  hanami_data:

networks:
  internal_network:
    internal: true
  external_network:
