import { MiAbuseUserReport } from '@/models/mikro-orm/AbuseUserReport';
import { MiAbuseReportNotificationRecipient } from '@/models/mikro-orm/AbuseReportNotificationRecipient';
import { MiAccessToken } from '@/models/mikro-orm/AccessToken';
import { MiAd } from '@/models/mikro-orm/Ad';
import { MiAnnouncement } from '@/models/mikro-orm/Announcement';
import { MiAnnouncementRead } from '@/models/mikro-orm/AnnouncementRead';
import { MiAntenna } from '@/models/mikro-orm/Antenna';
import { MiApp } from '@/models/mikro-orm/App';
import { MiAvatarDecoration } from '@/models/mikro-orm/AvatarDecoration';
import { MiAuthSession } from '@/models/mikro-orm/AuthSession';
import { MiBlocking } from '@/models/mikro-orm/Blocking';
import { MiChannelFollowing } from '@/models/mikro-orm/ChannelFollowing';
import { MiChannelFavorite } from '@/models/mikro-orm/ChannelFavorite';
import { MiClip } from '@/models/mikro-orm/Clip';
import { MiClipNote } from '@/models/mikro-orm/ClipNote';
import { MiClipFavorite } from '@/models/mikro-orm/ClipFavorite';
import { MiDriveFile } from '@/models/mikro-orm/DriveFile';
import { MiDriveFolder } from '@/models/mikro-orm/DriveFolder';
import { MiEmoji } from '@/models/mikro-orm/Emoji';
import { MiFollowing } from '@/models/mikro-orm/Following';
import { MiFollowRequest } from '@/models/mikro-orm/FollowRequest';
import { MiGalleryLike } from '@/models/mikro-orm/GalleryLike';
import { MiGalleryPost } from '@/models/mikro-orm/GalleryPost';
import { MiHashtag } from '@/models/mikro-orm/Hashtag';
import { MiInstance } from '@/models/mikro-orm/Instance';
import { MiMeta } from '@/models/mikro-orm/Meta';
import { MiModerationLog } from '@/models/mikro-orm/ModerationLog';
import { MiMuting } from '@/models/mikro-orm/Muting';
import { MiRenoteMuting } from '@/models/mikro-orm/RenoteMuting';
import { MiNote } from '@/models/mikro-orm/Note';
import { MiNoteFavorite } from '@/models/mikro-orm/NoteFavorite';
import { MiNoteReaction } from '@/models/mikro-orm/NoteReaction';
import { MiNoteThreadMuting } from '@/models/mikro-orm/NoteThreadMuting';
import { MiNoteUnread } from '@/models/mikro-orm/NoteUnread';
import { MiPage } from '@/models/mikro-orm/Page';
import { MiPageLike } from '@/models/mikro-orm/PageLike';
import { MiPasswordResetRequest } from '@/models/mikro-orm/PasswordResetRequest';
import { MiPoll } from '@/models/mikro-orm/Poll';
import { MiPollVote } from '@/models/mikro-orm/PollVote';
import { MiPromoNote } from '@/models/mikro-orm/PromoNote';
import { MiPromoRead } from '@/models/mikro-orm/PromoRead';
import { MiRegistrationTicket } from '@/models/mikro-orm/RegistrationTicket';
import { MiRegistryItem } from '@/models/mikro-orm/RegistryItem';
import { MiRelay } from '@/models/mikro-orm/Relay';
import { MiSignin } from '@/models/mikro-orm/Signin';
import { MiSwSubscription } from '@/models/mikro-orm/SwSubscription';
import { MiUsedUsername } from '@/models/mikro-orm/UsedUsername';
import { MiUser } from '@/models/mikro-orm/User';
import { MiUserIp } from '@/models/mikro-orm/UserIp';
import { MiUserKeypair } from '@/models/mikro-orm/UserKeypair';
import { MiUserList } from '@/models/mikro-orm/UserList';
import { MiUserListFavorite } from '@/models/mikro-orm/UserListFavorite';
import { MiUserListMembership } from '@/models/mikro-orm/UserListMembership';
import { MiUserNotePining } from '@/models/mikro-orm/UserNotePining';
import { MiUserPending } from '@/models/mikro-orm/UserPending';
import { MiUserProfile } from '@/models/mikro-orm/UserProfile';
import { MiUserPublickey } from '@/models/mikro-orm/UserPublickey';
import { MiUserSecurityKey } from '@/models/mikro-orm/UserSecurityKey';
import { MiWebhook } from '@/models/mikro-orm/Webhook';
import { MiSystemWebhook } from '@/models/mikro-orm/SystemWebhook';
import { MiChannel } from '@/models/mikro-orm/Channel';
import { MiRetentionAggregation } from '@/models/mikro-orm/RetentionAggregation';
import { MiRole } from '@/models/mikro-orm/Role';
import { MiRoleAssignment } from '@/models/mikro-orm/RoleAssignment';
import { MiFlash } from '@/models/mikro-orm/Flash';
import { MiFlashLike } from '@/models/mikro-orm/FlashLike';
import { MiUserMemo } from '@/models/mikro-orm/UserMemo';
import { MiBubbleGameRecord } from '@/models/mikro-orm/BubbleGameRecord';
import { MiReversiGame } from '@/models/mikro-orm/ReversiGame';
import { BaseMiRepository } from './BaseMiRepository';

export class AbuseUserReportsRepository extends BaseMiRepository<MiAbuseUserReport> {}
export class AbuseReportNotificationRecipientRepository extends BaseMiRepository<MiAbuseReportNotificationRecipient> {}
export class AccessTokensRepository extends BaseMiRepository<MiAccessToken> {}
export class AdsRepository extends BaseMiRepository<MiAd> {}
export class AnnouncementsRepository extends BaseMiRepository<MiAnnouncement> {}
export class AnnouncementReadsRepository extends BaseMiRepository<MiAnnouncementRead> {}
export class AntennasRepository extends BaseMiRepository<MiAntenna> {}
export class AppsRepository extends BaseMiRepository<MiApp> {}
export class AvatarDecorationsRepository extends BaseMiRepository<MiAvatarDecoration> {}
export class AuthSessionsRepository extends BaseMiRepository<MiAuthSession> {}
export class BlockingsRepository extends BaseMiRepository<MiBlocking> {}
export class ChannelFollowingsRepository extends BaseMiRepository<MiChannelFollowing> {}
export class ChannelFavoritesRepository extends BaseMiRepository<MiChannelFavorite> {}
export class ClipsRepository extends BaseMiRepository<MiClip> {}
export class ClipNotesRepository extends BaseMiRepository<MiClipNote> {}
export class ClipFavoritesRepository extends BaseMiRepository<MiClipFavorite> {}
export class DriveFilesRepository extends BaseMiRepository<MiDriveFile> {}
export class DriveFoldersRepository extends BaseMiRepository<MiDriveFolder> {}
export class EmojisRepository extends BaseMiRepository<MiEmoji> {}
export class FollowingsRepository extends BaseMiRepository<MiFollowing> {}
export class FollowRequestsRepository extends BaseMiRepository<MiFollowRequest> {}
export class GalleryLikesRepository extends BaseMiRepository<MiGalleryLike> {}
export class GalleryPostsRepository extends BaseMiRepository<MiGalleryPost> {}
export class HashtagsRepository extends BaseMiRepository<MiHashtag> {}
export class InstancesRepository extends BaseMiRepository<MiInstance> {}
export class MetasRepository extends BaseMiRepository<MiMeta> {}
export class ModerationLogsRepository extends BaseMiRepository<MiModerationLog> {}
export class MutingsRepository extends BaseMiRepository<MiMuting> {}
export class RenoteMutingsRepository extends BaseMiRepository<MiRenoteMuting> {}
export class NotesRepository extends BaseMiRepository<MiNote> {}
export class NoteFavoritesRepository extends BaseMiRepository<MiNoteFavorite> {}
export class NoteReactionsRepository extends BaseMiRepository<MiNoteReaction> {}
export class NoteThreadMutingsRepository extends BaseMiRepository<MiNoteThreadMuting> {}
export class NoteUnreadsRepository extends BaseMiRepository<MiNoteUnread> {}
export class PagesRepository extends BaseMiRepository<MiPage> {}
export class PageLikesRepository extends BaseMiRepository<MiPageLike> {}
export class PasswordResetRequestsRepository extends BaseMiRepository<MiPasswordResetRequest> {}
export class PollsRepository extends BaseMiRepository<MiPoll> {}
export class PollVotesRepository extends BaseMiRepository<MiPollVote> {}
export class PromoNotesRepository extends BaseMiRepository<MiPromoNote> {}
export class PromoReadsRepository extends BaseMiRepository<MiPromoRead> {}
export class RegistrationTicketsRepository extends BaseMiRepository<MiRegistrationTicket> {}
export class RegistryItemsRepository extends BaseMiRepository<MiRegistryItem> {}
export class RelaysRepository extends BaseMiRepository<MiRelay> {}
export class SigninsRepository extends BaseMiRepository<MiSignin> {}
export class SwSubscriptionsRepository extends BaseMiRepository<MiSwSubscription> {}
export class UsedUsernamesRepository extends BaseMiRepository<MiUsedUsername> {}
export class UsersRepository extends BaseMiRepository<MiUser> {}
export class UserIpsRepository extends BaseMiRepository<MiUserIp> {}
export class UserKeypairsRepository extends BaseMiRepository<MiUserKeypair> {}
export class UserListsRepository extends BaseMiRepository<MiUserList> {}
export class UserListFavoritesRepository extends BaseMiRepository<MiUserListFavorite> {}
export class UserListMembershipsRepository extends BaseMiRepository<MiUserListMembership> {}
export class UserNotePiningsRepository extends BaseMiRepository<MiUserNotePining> {}
export class UserPendingsRepository extends BaseMiRepository<MiUserPending> {}
export class UserProfilesRepository extends BaseMiRepository<MiUserProfile> {}
export class UserPublickeysRepository extends BaseMiRepository<MiUserPublickey> {}
export class UserSecurityKeysRepository extends BaseMiRepository<MiUserSecurityKey> {}
export class WebhooksRepository extends BaseMiRepository<MiWebhook> {}
export class SystemWebhooksRepository extends BaseMiRepository<MiSystemWebhook> {}
export class ChannelsRepository extends BaseMiRepository<MiChannel> {}
export class RetentionAggregationsRepository extends BaseMiRepository<MiRetentionAggregation> {}
export class RolesRepository extends BaseMiRepository<MiRole> {}
export class RoleAssignmentsRepository extends BaseMiRepository<MiRoleAssignment> {}
export class FlashsRepository extends BaseMiRepository<MiFlash> {}
export class FlashLikesRepository extends BaseMiRepository<MiFlashLike> {}
export class UserMemoRepository extends BaseMiRepository<MiUserMemo> {}
export class BubbleGameRecordsRepository extends BaseMiRepository<MiBubbleGameRecord> {}
export class ReversiGamesRepository extends BaseMiRepository<MiReversiGame> {}
